const ENUMS = {
  USER_ROLES: {
    ADMIN: 'ADMIN',
    USER: 'USER',
    PRODUCT_MANAGER: 'PRODUCT_MANAGER',
    SUPPORT: 'SUPPORT',
  },
  PRODUCT_STATUSES: {
    IN_STOCK: 'IN_STOCK',
    WARNING: 'WARNING',
    OUT_OF_STOCK: 'OUT_OF_STOCK',
  },
  ORDER_STATUSES: {
    WATING_FOR_APPROVEMENT: 'WATING_FOR_APPROVEMENT',
    APPROVED: 'APPROVED',
    DECLINED: 'DECLINED',
    IN_PROGRESS: 'IN_PROGRESS',
    DELIVERING: 'DELIVERING',
    DELIVERED: 'DELIVERED',
  },
};
module.exports = ENUMS;
