const ENUMS = {
  USER_ROLES: {
    ADMIN: 'ADMIN',
    USER: 'USER',
    PRODUCT_MANAGER: 'PRODUCT_MANAGER',
    SUPPORT: 'SUPPORT',
  },
  USER_PERMISSIONS: {
    CREATE_ANY: 'CREATE_ANY',
    READ_ANY: 'READ_ANY',
    UPDATE_ANY: 'UPDATE_ANY',
    DELETE_ANY: 'DELETE_ANY',
    CREATE_OWN: 'CREATE_OWN',
    READ_OWN: 'READ_OWN',
    UPDATE_OWN: 'UPDATE_OWN',
    DELETE_OWN: 'DELETE_OWN',
  },
  PRODUCT_STATUSES: {
    IN_STOCK: 'IN_STOCK',
    WARNING: 'WARNING',
    OUT_OF_STOCK: 'OUT_OF_STOCK',
  },
  PRODUCT_TYPES: {
    DIGITAL: 'DIGITAL',
    PHISYCAL: 'PHISYCAL',
  },
  ORDER_STATUSES: {
    WATING_FOR_APPROVEMENT: 'WATING_FOR_APPROVEMENT',
    APPROVED: 'APPROVED',
    DECLINED: 'DECLINED',
    IN_PROGRESS: 'IN_PROGRESS',
    DELIVERING: 'DELIVERING',
    DELIVERED: 'DELIVERED',
  },
  PAYMENT_PORTS: {
    MELLAT: 'MELLAT',
    PAYPAL: 'PAYPAL',
  },
};
module.exports = ENUMS;
